import { MigrationInterface, QueryRunner } from 'typeorm';

export class LocalSchema1690000000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    // The supplied 2023 backup uses descriptive characteristics, not size/price variants.
    // Keep those rows intact rather than guessing prices or discarding their text.
    if (await queryRunner.hasTable('parametrs') && await queryRunner.hasColumn('parametrs', 'title') &&
        !await queryRunner.hasColumn('parametrs', 'size')) {
      await queryRunner.query('ALTER TABLE "parametrs" RENAME TO "parametrs_legacy"');
    }
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS category (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(500) NOT NULL, "order" integer NOT NULL DEFAULT 0, "isActive" boolean NOT NULL DEFAULT true
      );
      ALTER TABLE category ALTER COLUMN "order" SET DEFAULT 0;
      CREATE TABLE IF NOT EXISTS catalog (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar NOT NULL, description varchar NOT NULL,
        articule integer NOT NULL, price integer NOT NULL, photo varchar(200),
        "isActive" boolean NOT NULL DEFAULT true, "categoryId" integer REFERENCES category(id)
      );
      ALTER TABLE catalog ADD COLUMN IF NOT EXISTS articule integer;
      UPDATE catalog SET articule = id WHERE articule IS NULL;
      ALTER TABLE catalog ALTER COLUMN articule SET NOT NULL;
      CREATE TABLE IF NOT EXISTS parametrs (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        size integer NOT NULL, cost integer NOT NULL,
        "catalogId" integer REFERENCES catalog(id) ON DELETE CASCADE
      );
      CREATE TABLE IF NOT EXISTS images (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        image varchar(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true,
        "catalogId" integer REFERENCES catalog(id)
      );
      DO $$ BEGIN
        CREATE TYPE order_status_enum AS ENUM ('start','confirmed','cancelled','completed','refusal');
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
      DO $$ BEGIN
        CREATE TYPE product_color_enum AS ENUM ('white','black','lime','sky','purple','pink','rose','gray');
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;
      CREATE TABLE IF NOT EXISTS "order" (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fio varchar NOT NULL, phone varchar NOT NULL, email varchar NOT NULL, adres varchar NOT NULL,
        status order_status_enum NOT NULL DEFAULT 'start', comment varchar, date varchar NOT NULL
      );
      CREATE TABLE IF NOT EXISTS product (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title varchar NOT NULL, articule integer NOT NULL, price integer NOT NULL,
        size integer NOT NULL, quantity integer NOT NULL, lent boolean NOT NULL DEFAULT false,
        color product_color_enum DEFAULT 'white', text varchar, "orderId" integer REFERENCES "order"(id)
      );
    `);
  }

  async down(): Promise<void> {
    throw new Error('This data-preserving migration is forward-only. Restore a database backup to roll back.');
  }
}
